# 
# .github/workflows/deploy.yml
# نشر تلقائي إلى GitHub Pages. يتعامل مع وجود/عدم وجود package-lock.json.
#
name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm" # يعمل أفضل مع package-lock.json، لكنه لا يعيق البناء عند عدم وجوده

      - name: Install dependencies
        # إن وُجد lockfile نستخدم npm ci، وإلا نستخدم npm install
        run: |
          if [ -f package-lock.json ]; then
            echo "Found package-lock.json → running npm ci"
            npm ci
          else
            echo "No package-lock.json → running npm install"
            npm install --no-audit --no-fund
          fi

      - name: Build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4
